[[rules]]
name = "rule1"
rule = "class_implements 'Foo' and includes 'Bar' then ERROR"

[[rules]]
name = "rule2"
rule = "class_extends 'BaseMediator' and import 'component' then ERROR"

[[rules]]
name = "rule3"
rule = "method_returns 'Observable' and not name_matches '\\$$' then ERROR"
